services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-permit-manager-web
    working_dir: /app/web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - web_node_modules:/app/web/node_modules
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: 0.0.0.0
      PORT: "3000"
    stdin_open: true
    tty: true

volumes:
  web_node_modules:
